# Generated by Django 5.0.2 on 2024-02-24 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_manager_participant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
