# Generated by Django 5.0.2 on 2024-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
