# Generated by Django 5.0.2 on 2024-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_gender_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hobby",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="user",
            name="points",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
