# Generated by Django 5.0.2 on 2024-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
