# Generated by Django 5.0.2 on 2024-02-24 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_check"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Check",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
