# Generated by Django 5.0.2 on 2024-02-24 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
