# Generated by Django 5.0.2 on 2024-02-27 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_participant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
    ]
