# Generated by Django 5.0.2 on 2024-02-27 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_participant_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
