# Generated by Django 5.0.2 on 2024-02-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Location_Type",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Location Type",
                "verbose_name_plural": "Location Types",
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("total_points", models.PositiveIntegerField()),
                ("total_duration", models.PositiveIntegerField()),
                ("max_people", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.participant",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest",
                "verbose_name_plural": "Quests",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("points", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
                (
                    "location_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.location_type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.CreateModel(
            name="Quest_Task",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("day_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quest"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Task",
                "verbose_name_plural": "Quest Tasks",
            },
        ),
        migrations.CreateModel(
            name="User_Quest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quest"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quest",
                "verbose_name_plural": "User Quests",
            },
        ),
    ]
