# Generated by Django 5.0.2 on 2024-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_category_location_type_quest_task_quest_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.TextField(default='none'),
        ),
    ]
