# Generated by Django 5.0.2 on 2024-02-28 09:08

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_task_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_uuid', models.UUIDField()),
                ('quest_vector', pgvector.django.VectorField(dimensions=384)),
            ],
            options={
                'db_table': 'quest_embeddings',
                'managed': False,
            },
        ),
    ]
