# Generated by Django 5.0.2 on 2024-02-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_questembeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.AddField(
            model_name='task',
            name='creator_uuid',
            field=models.ForeignKey(default='4f852bcf-cc21-415a-a3a7-65c4d0119df4', on_delete=django.db.models.deletion.CASCADE, to='core.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_quest',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
