# Generated by Django 5.0.2 on 2024-02-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_task_created_by_task_creator_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_quest',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
